import { StyleSheet, Dimensions, Platform } from "react-native";
import colors from "../../../theme/colors";
const { width } = Dimensions.get("window");
const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    centered: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
        backgroundColor: colors.background,
    },
    errorText: {
        color: colors.error,
        textAlign: "center",
        marginBottom: 10,
    },
    retryButton: {
        marginTop: 20,
        backgroundColor: colors.primary,
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    retryButtonText: {
        color: colors.textPrimary,
    },
    scrollViewContent: { paddingBottom: 80 },
    headerImage: { width: "100%", height: 250, resizeMode: "cover" },
    contentContainer: {
        backgroundColor: colors.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        marginTop: -20,
        paddingHorizontal: 20,
        paddingTop: 24,
    },
    nameStatusRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 4,
    },
    placeName: {
        fontSize: 26,
        color: colors.textPrimary,
        flex: 1,
        marginRight: 10,
    },
    statusBadge: {
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 12,
    },
    statusBadgeOpen: {
        backgroundColor: colors.successLight,
    },
    statusBadgeClosed: {
        backgroundColor: colors.errorLight,
    },
    statusBadgeText: {
        fontSize: 12,
    },
    statusBadgeTextOpen: {
        color: colors.successDark,
    },
    statusBadgeTextClosed: {
        color: colors.errorDark,
    },
    placeCategory: {
        fontSize: 15,
        color: colors.textSecondary,
        marginBottom: 16,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    infoIcon: {
        marginRight: 12,
    },
    infoText: {
        fontSize: 14,
        color: colors.textPrimary,
        flex: 1,
    },
    infoTextAddress: {
        fontSize: 14,
        color: colors.textPrimary,
        flex: 1,
        marginRight: 10,
    },
    distanceContainer: {
        flexDirection: "row",
        alignItems: "center",
    },
    distanceText: {
        fontSize: 14,
        color: colors.textPrimary,
    },
    ratingsContainer: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        paddingVertical: 16,
        paddingHorizontal: 16,
        marginTop: 20,
        marginBottom: 20,
    },
    ratingsWrapper: {
        paddingHorizontal: 20,
    },
    topRatingsRow: {
        flexDirection: "row",
        justifyContent: "space-around",
        marginBottom: 16,
    },
    topRatingItem: {
        alignItems: "center",
    },
    topRatingLabel: {
        fontSize: 13,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    topRatingValueRow: {
        flexDirection: "row",
        alignItems: "center",
    },
    topRatingValue: {
        fontSize: 18,
        color: colors.textPrimary,
    },
    topRatingCount: {
        fontSize: 14,
        color: colors.textSecondary,
        marginLeft: 4,
    },
    ratingDivider: {
        height: 1,
        backgroundColor: colors.divider,
        marginVertical: 12,
    },
    detailedRatings: {},
    detailedRatingRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    detailedRatingLabel: {
        fontSize: 14,
        color: colors.textPrimary,
        width: 80,
    },
    detailedRatingValue: {
        fontSize: 14,
        color: colors.textPrimary,
        width: 30,
        textAlign: "right",
        marginRight: 12,
    },
    ratingBarBackground: {
        flex: 1,
        height: 8,
        backgroundColor: colors.divider,
        borderRadius: 4,
        overflow: "hidden",
    },
    ratingBarFill: {
        height: "100%",
        backgroundColor: colors.star,
        borderRadius: 4,
    },
    evaluateButton: {
        flexDirection: "row",
        backgroundColor: colors.primary,
        paddingVertical: 14,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        marginTop: 10,
        marginBottom: 20,
    },
    evaluateButtonText: {
        color: colors.textPrimary,
        fontSize: 16,
    },
    reviewsSectionContainer: {
        marginTop: 24,
    },
    sectionTitle: {
        fontSize: 20,
        color: colors.textPrimary,
        marginBottom: 16,
        marginTop: 24,
    },
    reviewCardContainer: {
        flexDirection: "row",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: colors.divider,
    },
    reviewAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 12,
        backgroundColor: colors.divider,
    },
    reviewContent: {
        flex: 1,
    },
    reviewHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 4,
    },
    reviewUserName: {
        fontSize: 15,
        color: colors.textPrimary,
    },
    reviewTimeAgo: {
        fontSize: 12,
        color: colors.textSecondary,
    },
    reviewRating: {
        flexDirection: "row",
        alignItems: "center",
    },
    reviewRatingValue: {
        fontSize: 14,
        color: colors.textPrimary,
    },
    reviewText: {
        fontSize: 14,
        color: colors.textPrimary,
        lineHeight: 20,
    },
    seeAllReviewsButton: {
        marginTop: 16,
        paddingVertical: 12,
        alignItems: "center",
        borderWidth: 1,
        borderColor: colors.primary,
        borderRadius: 8,
    },
    seeAllReviewsButtonText: {
        fontSize: 15,
        color: colors.primary,
    },
    mapPlaceholderContainer: {
        width: "100%",
        height: 180,
        borderRadius: 12,
        backgroundColor: colors.divider,
        justifyContent: "center",
        alignItems: "center",
        overflow: "hidden",
        marginBottom: 20,
        position: "relative",
    },
    mapView: {
        width: "100%",
        height: "100%",
    },
    mapDirectionsButton: {
        position: "absolute",
        bottom: 12,
        right: 12,
        backgroundColor: colors.primary,
        borderRadius: 20,
        width: 40,
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 4,
    },
    hoursContainer: {
        backgroundColor: colors.surface,
        padding: 16,
        borderRadius: 12,
        marginBottom: 20,
    },
    hourRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
    },
    hourIcon: {
        marginRight: 10,
    },
    hourDay: {
        fontSize: 14,
        color: colors.textSecondary,
        width: 100,
    },
    hourTime: {
        fontSize: 14,
        color: colors.textPrimary,
    },
    hourTimeHighlight: {
        color: colors.successDark,
    },
    tagsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        marginBottom: 16,
    },
    tag: {
        backgroundColor: colors.tagBackground,
        borderRadius: 15,
        paddingVertical: 6,
        paddingHorizontal: 14,
        marginRight: 8,
        marginBottom: 8,
    },
    tagText: {
        color: colors.tagText,
        fontSize: 13,
    },
    topBar: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        paddingTop: Platform.OS === "ios" ? 50 : 20,
        height: Platform.OS === "ios" ? 90 : 60,
        paddingHorizontal: 12,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        zIndex: 20,
        backgroundColor: "transparent",
    },
    topBarRight: { flexDirection: "row", alignItems: "center", gap: 8 },
    topBarButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(0,0,0,0.5)",
        alignItems: "center",
        justifyContent: "center",
    },
    emptyReviewsText: {
        fontSize: 14,
        color: colors.textSecondary,
        textAlign: "center",
        paddingVertical: 20,
    },
    emptyInfoText: {
        fontSize: 14,
        color: colors.textSecondary,
        textAlign: "center",
        paddingVertical: 12,
    },
});
export default styles;
