import { StyleSheet, Platform } from "react-native";
import colors from "../../../../theme/colors";
const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollViewContent: {
        paddingBottom: 120,
    },
    imageContainer: { width: "100%", height: 220 },
    placeImage: { width: "100%", height: "100%", resizeMode: "cover" },
    placeNameOverlay: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
    },
    placeName: {
        fontSize: 26,
        fontWeight: "bold",
        color: "#FFF",
        textShadowColor: "rgba(0, 0, 0, 0.75)",
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 5,
    },
    contentCard: {
        backgroundColor: colors.background,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        marginTop: -20,
        padding: 24,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -5 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 10,
    },
    ratingGroup: { marginBottom: 28 },
    ratingLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: colors.textPrimary,
        marginBottom: 12,
    },
    iconRatingContainer: {
        flexDirection: "row",
        gap: 16,
    },
    inputRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 15,
    },
    inputField: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 55,
        fontSize: 16,
        color: colors.textPrimary,
        width: "48%",
    },
    dateInputContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: colors.surface,
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 55,
        marginBottom: 15,
    },
    dateText: {
        fontSize: 16,
        color: colors.textPrimary,
    },
    experienceInput: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        paddingHorizontal: 15,
        paddingVertical: 15,
        minHeight: 140,
        fontSize: 16,
        color: colors.textPrimary,
        textAlignVertical: "top",
    },
    publishButtonContainer: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        padding: 20,
        paddingBottom: Platform.OS === "ios" ? 30 : 20,
        backgroundColor: colors.background,
        borderTopWidth: 1,
    },
    publishButton: {
        backgroundColor: colors.primary,
        borderRadius: 12,
        height: 55,
        alignItems: "center",
        justifyContent: "center",
    },
    publishButtonDisabled: {
        opacity: 0.7,
    },
    publishButtonText: {
        color: "#FFF",
        fontSize: 18,
        fontWeight: "bold",
    },
});
export default styles;
