import { StyleSheet } from "react-native";
import colors from "../../../../theme/colors";
export default StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    headerBar: {
        height: 56,
        alignItems: "center",
        justifyContent: "center",
    },
    headerBack: { position: "absolute", left: 12, top: 14 },
    headerTitle: { fontSize: 18, color: colors.textPrimary },
    centered: { flex: 1, alignItems: "center", justifyContent: "center" },
    summaryCard: {
        marginHorizontal: 16,
        padding: 16,
        borderRadius: 12,
        backgroundColor: colors.surface,
        borderWidth: 1,
        borderColor: "#2d3444",
    },
    summaryRow: { flexDirection: "row", justifyContent: "space-between" },
    summaryCol: { flex: 1 },
    summaryLabel: { color: colors.textSecondary, marginBottom: 6 },
    summaryValueRow: { flexDirection: "row", alignItems: "center" },
    summaryValue: { color: colors.textPrimary, fontSize: 18 },
    summaryCount: { color: colors.textSecondary, marginLeft: 6 },
    detailRows: { marginTop: 12 },
    detailRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    detailLabel: { color: colors.textSecondary },
    detailValue: { color: colors.textPrimary },
    tabsRow: {
        flexDirection: "row",
        paddingHorizontal: 16,
        marginTop: 16,
        marginBottom: 8,
    },
    tabButton: { marginRight: 24 },
    tabLabel: { color: colors.textSecondary },
    tabLabelActive: { color: colors.primary },
    tabIndicator: {
        height: 2,
        backgroundColor: colors.textPrimary,
        borderRadius: 1,
        marginTop: 6,
    },
    reviewRow: {
        flexDirection: "row",
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    avatarImage: {
        width: 44,
        height: 44,
        borderRadius: 22,
        marginRight: 12,
        backgroundColor: colors.divider,
    },
    reviewCol: { flex: 1 },
    reviewHeader: { flexDirection: "row", justifyContent: "space-between" },
    userName: { color: colors.textPrimary },
    ratingBadge: { flexDirection: "row", alignItems: "center" },
    ratingText: { color: colors.textPrimary, marginLeft: 4 },
    timeAgo: { color: colors.textSecondary, marginTop: 2 },
    comment: { color: colors.textPrimary, marginTop: 8 },
});
