import { StyleSheet } from "react-native";
import colors from "../../../theme/colors";

const styles = StyleSheet.create({
  container: { flex: 1 },
  scrollViewContent: { paddingBottom: 80 },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 16,
  },
  username: { fontSize: 22, fontWeight: "800", color: colors.textPrimary },

  profileInfoContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    marginRight: 24,
  },
  followInfo: { alignItems: "center", marginRight: 20 },
  followCount: { fontSize: 18, fontWeight: "800", color: colors.textPrimary },
  followLabel: { fontSize: 12, color: colors.textSecondary },

  bioText: {
    fontSize: 14,
    color: colors.textSecondary,
    paddingHorizontal: 20,
    marginBottom: 20,
  },

  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 12,
    marginHorizontal: 20,
    paddingVertical: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.divider,
  },
  statItem: { alignItems: "center" },
  statLabel: { fontSize: 12, color: colors.textSecondary, marginBottom: 4 },
  statValue: { fontSize: 24, fontWeight: "800", color: colors.textPrimary },

  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 18,
    marginBottom: 10,
  },
  sectionTitle: { fontSize: 18, fontWeight: "800", color: colors.textPrimary },
  seeAllText: { color: colors.primary, fontSize: 14, fontWeight: "700" },

  horizontalListContent: { paddingHorizontal: 20 },

  visitedCard: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    marginRight: 12,
    overflow: "hidden",
  },
  visitedImage: {
    width: "100%",
    height: "100%",
  },
  visitedPlaceholder: {
    backgroundColor: colors.border,
  },
  visitedTitle: {
    position: "absolute",
    bottom: 6,
    left: 6,
    right: 6,
    fontSize: 12,
    fontWeight: "700",
    color: colors.surface,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.35)",
    borderRadius: 6,
    paddingVertical: 2,
    paddingHorizontal: 6,
    overflow: "hidden",
  },

  favCard: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.divider,
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  favImage: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
  },
  favImagePlaceholder: {
    backgroundColor: colors.border,
    width: "100%",
    height: "100%",
  },
  favTitle: {
    position: "absolute",
    bottom: 6,
    left: 6,
    right: 6,
    fontSize: 11,
    fontWeight: "700",
    color: colors.surface,
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.4)",
    borderRadius: 6,
    overflow: "hidden",
    paddingVertical: 1,
  },
  favAddCard: {
    width: 100,
    height: 100,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.divider,
    backgroundColor: colors.surface,
    marginRight: 12,
    alignItems: "center",
    justifyContent: "center",
  },

  listsContainer: { paddingHorizontal: 20, marginTop: 8 },
  listItem: {
    backgroundColor: colors.surface,
    borderColor: colors.divider,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginBottom: 10,
  },
  listItemText: { color: colors.textPrimary, fontSize: 14, fontWeight: "700" },

  menuOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.25)",
    zIndex: 5,
  },
  menuCard: {
    position: "absolute",
    right: 16,
    top: 60,
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingVertical: 8,
    width: 200,
    zIndex: 6,
    borderWidth: 1,
    borderColor: colors.divider,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 6,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 14,
  },
  menuItemIcon: { marginRight: 10 },
  menuItemText: { color: colors.textPrimary, fontSize: 14, fontWeight: "700" },

  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  loadingContainerPaddingTop: { paddingTop: 40 },
  loadingText: { color: colors.textSecondary, marginTop: 8, fontSize: 14 },
  errorBox: { paddingHorizontal: 20, marginTop: 16 },
  errorText: { color: colors.error },

  emptyText: { color: colors.textSecondary, paddingHorizontal: 20 },

  sheetOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  sheetCard: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 1,
    borderColor: colors.divider,
    padding: 12,
  },
  sheetButton: {
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.divider,
    borderRadius: 10,
    marginBottom: 8,
    backgroundColor: colors.surface,
  },
  sheetButtonText: {
    color: colors.textPrimary,
    fontWeight: "700",
  },
  sheetButtonPrimary: {
    paddingVertical: 14,
    alignItems: "center",
    borderRadius: 10,
    marginTop: 10,
    backgroundColor: colors.primary,
  },
  sheetButtonPrimaryText: {
    color: colors.onPrimary || colors.surface,
    fontWeight: "800",
  },
});

export default styles;
